import { useNavigate } from 'react-router-dom';
import { companies, jobs } from '../data/mockJobs';
import CompanyLogo from '../components/CompanyLogo';

export default function Home() {
  const navigate = useNavigate();
  const submit = (e) => { e.preventDefault(); navigate(`/jobs?q=${encodeURIComponent(new FormData(e.currentTarget).get('q') || '')}`); };
  return <main aria-label="Home">
    <section className="hero-v2"><div className="shell hero-grid"><div className="hero-copy"><div className="eyebrow"><i /> Multi-source job intelligence</div><h1>Find work that<br /><em>fits your life.</em></h1><p>One place to compare opportunities from the web’s best job sources — with the detail needed to make a better call.</p><form className="hero-search" onSubmit={submit}><div><label htmlFor="home-search">What are you looking for?</label><input id="home-search" name="q" placeholder="e.g. frontend engineer" /></div><div className="search-location"><label>Where?</label><input placeholder="India or Remote" /></div><button>Find jobs <span>→</span></button></form><div className="popular"><span>Popular:</span>{['Software engineer','Product designer','Data analyst','Internships'].map(x => <button key={x} onClick={() => navigate(`/jobs?q=${x}`)}>{x}</button>)}</div></div><aside className="hero-orbit"><div className="orbit-core"><small>ACTIVE<br />OPPORTUNITIES</small><strong>12,842</strong><span>across 14 sources</span></div><div className="orbit-tag t1">REMOTE +1,284</div><div className="orbit-tag t2">UPDATED NOW</div><div className="orbit-tag t3">94% MATCH</div></aside></div></section>
    <section className="metrics"><div className="shell metrics-grid"><div><b>14</b><span>sources compared</span></div><div><b>12k+</b><span>live opportunities</span></div><div><b>48h</b><span>average response window</span></div><div><b>4.8/5</b><span>job seeker rating</span></div></div></section>
    <section className="shell section"><div className="section-heading"><div><div className="eyebrow">Trending this week</div><h2>Roles worth a closer look.</h2></div><button className="text-button" onClick={() => navigate('/jobs')}>View all jobs →</button></div><div className="feature-grid">{jobs.slice(0,3).map((job, index) => <button className="featured-job" key={job.id} onClick={() => navigate(`/jobs/${job.id}`)}><span className="job-index">0{index + 1}</span><CompanyLogo companyLogo={job.companyLogo} logo={job.logo} company={job.company} /><div><h3>{job.title}</h3><p>{job.company} · {job.location}</p></div><strong>{job.salary}</strong><span className="arrow">↗</span></button>)}</div></section>

    <section className="company-band"><div className="shell"><div className="section-heading"><div><div className="eyebrow">Hiring now</div><h2>Great teams, open doors.</h2></div><p className="section-note">Explore companies with active roles, rich culture context, and clear job details.</p></div><div className="company-grid">{companies.map(c => <button className={`company-tile ${c.tone}`} key={c.name} onClick={() => navigate(`/jobs?q=${c.name}`)}><span>{c.name.slice(0,2)}</span><b>{c.name}</b><small>{c.count} open roles</small></button>)}</div></div></section>
    <section className="shell section split-section"><div><div className="eyebrow">A better way to compare</div><h2>More signal.<br />Less job-board hopping.</h2></div><div className="step-list"><article><span>01</span><div><h3>Search once</h3><p>We bring jobs from multiple sources into one useful view.</p></div></article><article><span>02</span><div><h3>Compare with context</h3><p>Sort by salary, location, skills, experience, work mode, and freshness.</p></div></article><article><span>03</span><div><h3>Apply with confidence</h3><p>Track every application and return to the original source in one click.</p></div></article></div></section>
    <section className="shell testimonial"><div className="quote-mark">“</div><blockquote>It feels less like scrolling listings and more like having a calm career copilot.</blockquote><div><b>Priya Nair</b><span>Product Designer, Bengaluru</span></div></section>
    <section className="shell final-cta"><div><div className="eyebrow">Your next chapter starts here</div><h2>Search better from today.</h2></div><button onClick={() => navigate('/auth')}>Create your profile <span>→</span></button></section>
  </main>;
}
