-- PostgreSQL / Supabase reference schema
create type user_role as enum ('candidate','recruiter','company_admin','platform_admin');
create table profiles (id uuid primary key references auth.users(id), role user_role default 'candidate', full_name text, headline text, about text, location text, expected_salary_min integer, expected_salary_max integer, availability text, avatar_url text, cover_url text, completion_score smallint default 0, created_at timestamptz default now());
create table companies (id uuid primary key default gen_random_uuid(), name text not null, slug text unique not null, logo_url text, overview text, culture text, employee_count text, locations jsonb default '[]');
create table jobs (id uuid primary key default gen_random_uuid(), source text not null, source_job_id text, source_url text not null, company_id uuid references companies(id), title text not null, description text, location text, work_mode text, employment_type text, experience_level text, salary_min integer, salary_max integer, currency text default 'INR', skills jsonb default '[]', posted_at timestamptz, expires_at timestamptz, unique(source, source_job_id));
create table saved_jobs (profile_id uuid references profiles(id), job_id uuid references jobs(id), created_at timestamptz default now(), primary key(profile_id,job_id));
create table applications (id uuid primary key default gen_random_uuid(), profile_id uuid references profiles(id), job_id uuid references jobs(id), status text default 'saved', source_redirected_at timestamptz, applied_at timestamptz, updated_at timestamptz default now());
create table resumes (id uuid primary key default gen_random_uuid(), profile_id uuid references profiles(id), storage_path text not null, original_name text, mime_type text, size_bytes bigint, parsed_data jsonb, is_primary boolean default false, created_at timestamptz default now());
create table notifications (id uuid primary key default gen_random_uuid(), profile_id uuid references profiles(id), kind text, title text, body text, read_at timestamptz, created_at timestamptz default now());
